# Generated by Django 4.2.1 on 2023-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
